openapi: 3.0.3
info:
  title: Greet User API
  description: API for Greeting user using grpc-client
  version: 1.0.0
 
servers:
  - url: http://localhost:8080/grpc
    description: Local development server
 
paths:
  /greet/{name}:
    get:
      summary: greet user
      tags:
        - Users
      responses:
        '200':
          description: greet user
          content:
            application/json:
              schema:
                type: string
    
