openapi: 3.0.3
info:
  title: Greet User API
  description: API for Greeting user using grpc-client
  version: 1.0.0
 
servers:
  - url: http://localhost:8080/grpc
    description: Local development server
 
paths:
  /greet/{name}:
    get:
      summary: Greet a user by name
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the person to greet
          schema:
            type: string
      responses:
        '200':
          description: Successful greeting
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    
